name: zaviato
description: A Digital Marketing Hero On Your Phone.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.4
  retrofit: 1.3.4
  event_bus: ^1.1.0
  provider: ^3.1.0
  kiwi: 2.0.0
  fluttertoast: ^6.0.1
  flutter_spinkit: ^4.0.0
  pull_to_refresh: ^1.5.6
  intl: ^0.16.1
  dots_indicator: ^1.0.0
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  flushbar:  1.10.4
  flutter_html: ^1.0.0
  flare_flutter: ^1.6.1
  path_provider: ^1.3.0
  dashed_container: ^1.0.1
  sembast: ^1.15.1
  rxbus: any
  percent_indicator: any
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+1
  app_settings: ^4.0.0
  package_info: ^0.4.0+16
  store_redirect: ^1.0.2
  compressimage: 0.1.1
  unique_identifier: ^0.0.3
  lottie: any
  image: any
  flutter_statusbarcolor: ^0.2.3
  dotted_line: ^2.0.2
  animated_text_kit: ^2.5.4
  get: ^3.13.2
  # animated_splash_screen: ^1.0.1+2
  # page_transition: ^1.1.7+6
  animated_splash: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  kiwi_generator: 2.0.0
  build_runner: any
  retrofit_generator: 1.3.4
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    - assets/common/
    - assets/fonts/

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karla-SemiBold.ttf
          weight: 800
